Hobby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views, settings
from orders.views import orders, akun_lain
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    url(r'^result/$', views.cari, name="cari"),
    path('menu/', include('menu.urls')),
    path('registrasi/', views.registrasi, name="register"),
    path('logout/', views.user_logout, name="logout"),
    path('user_login/', views.user_login, name="user_login"),
    path('cart/', include('cart.urls')),
    path('checkout/', include('orders.urls')),
    path('akun/', orders, name='akun'),
    path('tester/', views.test, name='test'),
    url(r'^(?P<username>[\w-]+)/$', akun_lain, name='akunLain'),
    

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.Cart, name='cart'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/$', views.tambahKeranjang, name='updateCart'),
    url(r'^(?P<id>[\w-]+)/$', views.removeKeranjang, name='removeKeranjang'),  
]

orders/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.Checkout, name='Checkout'),
    path('upload-bukti/', views.uploadBukti, name='uploadBukti'),
    path("pesanan-masuk/", views.pesanan_masuk, name="pesananMasuk"),
    url(r'^(?P<id>[\w-]+)/$', views.selesaikanOrder, name='selesaikanOrder'),
    url(r'^(?P<id>[\w-]+)/(?P<user>[\w-]+)/$', views.lihatOrder, name='lihatOrder'),
    
]

cart/models.py
from django.db import models
# from orders.models import order
from menu.models import Menu, Variation


class CartItem(models.Model):
    Cartt = models.ForeignKey('cart', on_delete=models.CASCADE, null=True, blank=True)
    products = models.ForeignKey(Menu, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation)
    quantity = models.IntegerField(default=1)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        try:
            return str(self.id)
        except:
            return self.products.title

class cart(models.Model):
    # items = models.ManyToManyField(CartItem, null=True, blank=True)
    # product = models.ManyToManyField(Menu, null=True, blank=True)
    # order_id = models.ForeignKey(order, on_delete=models.CASCADE, null=True)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    update = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return "Cart id: %s" %(self.id)

cart/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from menu.models import Menu, Variation
from .models import cart, CartItem
# Create your views here.


def Cart(request):
    try:
        the_id = request.session['cart_id']
        carts = cart.objects.get(id=the_id)
    except:
        the_id = None
    if the_id:
        new_total = 0
        for item in carts.cartitem_set.all():
            line_total = (item.products.hargaMenu - item.products.diskon) * item.quantity
            new_total += line_total
        # request.session['harga_total'] = line_total
        request.session['item_total'] = carts.cartitem_set.count()
        carts.total = new_total
        carts.save()
        context = {
            "cart": carts,
            'title': 'Keranjang',
            'subtitle': 'Keranjang',
        }
    else:
        empty_message = "Keranjang kamu masih kosong, Yuk belanja :)"
        context = {
            "empty": True,
            'title': 'Keranjang',
            'subtitle': 'Keranjang',
            'empty_message': empty_message,
        }

    template = "cart/view.html"
    return render(request, template, context)


def removeKeranjang(request, id):
    try:
        the_id = request.session['cart_id']
        carts = cart.objects.get(id=the_id)
    except:
        return HttpResponseRedirect(reverse('cart:cart'))
    cartitem = CartItem.objects.get(id=id)
    # cartitem.delete()
    cartitem.Cartt = None
    cartitem.save()

    return HttpResponseRedirect(reverse('cart:cart'))


def tambahKeranjang(request, category, slug):
    request.session.set_expiry(86400)

    try:
        the_id = request.session['cart_id']
    except:
        new_cart = cart()
        new_cart.save()
        request.session['cart_id'] = new_cart.id
        the_id = new_cart.id
    Cart = cart.objects.get(id=the_id)

    try:
        menu = Menu.objects.get(slug=slug)
    except Menu.DoesNotExist:
        pass
    except:
        pass

    variasiProduk = []
    if request.method == "POST":
        qty = request.POST['qty']
        for item in request.POST:
            key = item
            val = request.POST[key]
            try:
                v = Variation.objects.get(
                    product=menu, category__iexact=key, title__iexact=val)
                variasiProduk.append(v)
            except:
                pass

        cart_item = CartItem.objects.create(Cartt=Cart, products=menu)
        if len(variasiProduk) > 0:
            cart_item.variation.add(*variasiProduk)
        cart_item.quantity = qty
        cart_item.save()

        return HttpResponseRedirect(reverse('cart:cart'))

    return HttpResponseRedirect(reverse('cart:cart'))

cart/templates/cart/view.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
<title>Keranjang</title>
{% endblock title %}
{% block content %}


    {% if empty %}

    <h3>{{ empty_message }}</h3>

    {% else %}
    <table class="table mx-auto bg-light text-dark">
            <thead>
                <th>Nama Barang</th>
                <th>Harga Barang</th>
                <th>Jumlah</th>
                <th></th>
            </thead>
            <tfoot>
                <tr>
                    <td><a href="{% url 'orders:Checkout' %}" class="btn btn-light" >Checkout</a></td>
                    <td></td>
                    <td>Total : Rp. {{cart.total|intcomma}}</td>
                    <td></td>
                </tr>
            </tfoot>
        {% for item in cart.cartitem_set.all %}
            <tr>
                <td>
                    {{ item.products }}
                    
                    {% if item.variation.all %}
                    <ul>{% for subitem in item.variation.all %}
                            <li>{{ subitem.category|capfirst }} : {{ subitem.title|capfirst }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                        
                </td>
                <td>Rp. {{ item.products.hargaMenu|intcomma }}</td>
                <td>{{ item.quantity }}</td>
                <td><a href="{% url 'cart:removeKeranjang' item.id %}" class="text-white">Hapus</a></td>
            </tr>
        {% endfor %}
        
            
    </table>
    
    {% endif %}
{% endblock content %}
    