Hobby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views, settings
from orders.views import orders, akun_lain
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    url(r'^result/$', views.cari, name="cari"),
    path('menu/', include('menu.urls')),
    path('registrasi/', views.registrasi, name="register"),
    path('logout/', views.user_logout, name="logout"),
    path('user_login/', views.user_login, name="user_login"),
    path('cart/', include('cart.urls')),
    path('checkout/', include('orders.urls')),
    path('akun/', orders, name='akun'),
    path('tester/', views.test, name='test'),
    url(r'^(?P<username>[\w-]+)/$', akun_lain, name='akunLain'),
    

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.Cart, name='cart'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/$', views.tambahKeranjang, name='updateCart'),
    url(r'^(?P<id>[\w-]+)/$', views.removeKeranjang, name='removeKeranjang'),  
]

menu/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^(?P<category>[\w_]+)/$', views.indexCategory, name='category'),
    url(r'^(?P<category>[\w_]+)/(?P<slug>[\w-]+)$', views.beli, name='produkSatuan'),  
]

orders/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.Checkout, name='Checkout'),
    path('upload-bukti/', views.uploadBukti, name='uploadBukti'),
    path("pesanan-masuk/", views.pesanan_masuk, name="pesananMasuk"),
    url(r'^(?P<id>[\w-]+)/$', views.selesaikanOrder, name='selesaikanOrder'),
    url(r'^(?P<id>[\w-]+)/(?P<user>[\w-]+)/$', views.lihatOrder, name='lihatOrder'),
    
]

orders/models.py
import os
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

from cart.models import cart

User = get_user_model()

pilihanStatus = (
    ('Mulai','Mulai'),
    ('Ditolak','Ditolak'),
    ('Selesai','Selesai'),
)

class order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True, blank=True)
    order_id = models.CharField(max_length=120, default='test', unique=True)
    Cart = models.ForeignKey(cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=120, default='Mulai', choices=pilihanStatus)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    buktiPembayaran = models.FileField(upload_to = 'bukti_pembayaran/', blank=True, null=True)

    def __str__(self):
        return str("{}, {}, {}".format(self.timestamp, self.order_id,self.user))
        

orders/forms.py
from django import forms
from orders.models import order
from django.forms import ModelForm
from django.contrib.auth.models import User

class bukti_Pembayaran(forms.Form):
    buktiPembayaran = forms.FileField(required=True, label='')

orders/views.py
import time
from django.contrib.auth.decorators import login_required,user_passes_test
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from .models import order
from .utils import id_generatorOrder
from .forms import bukti_Pembayaran
from cart.models import cart, CartItem
from django.contrib.auth.models import User
from menu.models import Menu, Variation
# Create your views here.


def orders(request):
    profile = User.objects.select_related('userprofileinfo').get(id=request.user.id)
    orderan = order.objects.filter(user__id = request.user.id).order_by('-timestamp')

    context = {
        'profile':profile,
        'orderan':orderan,
    }
    template = 'orders/user.html'
    return render(request, template, context)

def akun_lain(request, username):
    profile = User.objects.select_related('userprofileinfo').get(username=username)
    orderan = order.objects.filter(user__id = request.user.id).order_by('-timestamp')

    context = {
        'profile':profile,
        'orderan':orderan,
    }
    template = 'orders/user.html'
    return render(request, template, context)


@login_required
def Checkout(request):
    try:
        the_id = request.session['cart_id']
        Cart = cart.objects.get(id=the_id)
    except:
        the_id = None
        return HttpResponseRedirect(reverse('cart:cart'))

    try:
        pesanan_baru = order.objects.get(Cart=Cart)
    except order.DoesNotExist:
        pesanan_baru = order()
        pesanan_baru.Cart = Cart
        pesanan_baru.user = request.user
        pesanan_baru.order_id = id_generatorOrder()
        pesanan_baru.save()
        del request.session['cart_id']
        del request.session['item_total']
    except:
        return HttpResponseRedirect(reverse('cart:cart'))
    
    orderan = order.objects.select_related('user','Cart').get(order_id=pesanan_baru.order_id)

    if pesanan_baru.status == "Selesai":
        # Cart.delete()
        del request.session['cart_id']
        del request.session['item_total']
        # del request.session['harga_total']
        return HttpResponseRedirect(reverse('cart:cart'))

    context = {
        'order_id': pesanan_baru.order_id,
        'orderan':orderan,
    }

    return render(request, 'orders/orders.html', context)


def uploadBukti(request):
    # model = buktiPembayaran
    uploaded = False
    id_transaksi = request.GET.get('idTrs')
    usrnm = request.GET.get('usrnm')
    if request.method == 'POST':
        form = bukti_Pembayaran(request.POST, request.FILES)
        uploaded_file = request.FILES['buktiPembayaran']
        fs = FileSystemStorage(location='media/bukti_pembayaran/')
        filename = fs.save(uploaded_file.name, uploaded_file)
        order_id = request.POST.get('order_id')
        user = request.POST.get('username')
        print(user)
        try:
            pesanan_masuk = order.objects.get(order_id = order_id,user__username=user)
            pesanan_masuk.buktiPembayaran = uploaded_file
            pesanan_masuk.save()
            uploaded = True
        except:
            Pesan = 'Username atau Id Transaksi tidak terdaftar'
        
    else:
        form = bukti_Pembayaran()
    context = {
        'pesan': 'Bukti pembayaran kamu berhasil di upload',
        'form': form,
        'uploaded': uploaded,
        'id_transaksi':id_transaksi,
        'usrnm':usrnm,
        # 'pesan':pesan,
    }
    template = 'orders/upload.html'
    return render(request, template, context)

@user_passes_test(lambda u: u.is_superuser)
def pesanan_masuk(request):
    orderan = order.objects.filter(status = 'Mulai').select_related('user','Cart').order_by('-timestamp')
    
    context = {
        'Orderan':orderan,
    }
    template = 'orders/pesanan_masuk.html'
    return render(request, template, context)

@user_passes_test(lambda u: u.is_superuser)
def selesaikanOrder(request, id):
    Order = order.objects.get(order_id=id)
    Order.status = ('Selesai')
    Order.save()

    return HttpResponseRedirect(reverse('orders:pesananMasuk'))

@user_passes_test(lambda u: u.is_superuser)
def lihatOrder(request, id, user):
    Order = order.objects.filter(order_id=id)
    cart_id = Order[0].Cart_id
    keranjang = CartItem.objects.select_related('Cartt','products').filter(Cartt_id = cart_id)
    total = keranjang[0].Cartt.total


    context = {
        'orderan' : Order,
        'keranjang' : keranjang,
        'total':total,
    }
    template = 'orders/detailOrder.html'
    return render(request, template, context)

orders/templates/orders/detailOrder.html
{% extends 'base.html' %}

{% block title %}
<title>Pesanan</title>
{% endblock title %}

{% block content %}
    {% comment %} <h3>{{ orderan.user.first_name }} {{orderan.user.last_name}}</h3> {% endcomment %}
    <table class="table table-striped mx-auto w-75 bg-light">
            <thead class="thead-dark">
                <th>No</th>
                <th>Nama Barang</th>
                <th>Harga Barang</th>
                <th>Jumlah</th>
                <th></th>
            </thead>
            <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Total : {{total}}</td>
                    <td></td>
                </tr>
            </tfoot>
        {% for item in keranjang %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>
                    {{ item.products.judulMenu }}
                    
                    {% if item.variation.all %}
                    <ul>{% for subitem in item.variation.all %}
                            <li>{{ subitem.category|capfirst }} : {{ subitem.title|capfirst }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                        
                </td>
                <td>{{ item.products.hargaMenu }}</td>
                <td>{{ item.quantity }}</td>
                <td></td>
            </tr>
        {% endfor %}
            
    </table>
{% endblock content %}

orders/templates/orders/orders.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}
<title>Detail Pemesanan</title>
{% endblock title %}

{% block content %}
<article class="post">
    <div class="container">
        <h3>Pesanan Kamu sedang di proses</h3>
        <table class="table table-bordered bg-light">
            <tbody>
                <tr>
                    <th scope="row">Username</th>
                    <td>{{orderan.user.username}}</td>
                </tr>
                <tr>
                    <th scope="row">Nama Lengkap</th>
                    <td colspan="2">{{orderan.user.first_name}} {{orderan.user.last_name}}</td>
                </tr>
                <tr>
                    <th scope="row">Id Transaksi</th>
                    <td>{{ order_id }}<br/><div class="text-danger">Harap Id Transaksi ini diingat untuk melakukan pembayaran</div></td>
                </tr>
                <tr>
                    <th scope="row">Harga Total</th>
                    <td colspan="2">Rp. {{ orderan.Cart.total|intcomma }}</td>
                </tr>
                <tr>
                    <th scope="row">Tanggal Transaksi</th>
                    <td colspan="2">{{orderan.timestamp|date:"l, d F Y"}}</td>
                </tr>
            </tbody>
        </table>
        <h3>Bayar pesanan kamu ke</h3>
        <h4>No Rekening BNI :</h4>
        <h4>0388705758 a/n Zulfikar Chamim</h4>
        <br/><br/>
        <h4><a class="btn btn-info" href="{% url 'orders:uploadBukti' %}?idTrs={{order_id}}&usrnm={{orderan.user.username}}">Upload Bukti Disni</a></h4>
        <h4><a class="btn btn-success" href="{% url 'menu:index' %}semua"> Yuk Belanja lagi!</a></h4>
    </div>
</article>
{% endblock content %}

orders/templates/orders/pesanan_masuk.html
{% extends 'base.html' %}
{% load humanize %}
{% block title %}
<title>Pesanan Masuk</title>
{% endblock title %}

{% block content %}
<div class="container">
<h2>Pesanan Masuk</h2>

<table class="table table-striped mx-auto w-100 bg-light link-dark">
    <thead class="thead-dark">
        <th>Tanggal</th>
        <th>ID Pesanan</th>
        <th>Nama Pelanggan</th>
        <th>Harga Total</th>
        <th>Bukti Pembayaran</th>
        <th>Status</th>
    </thead>
    <tfoot>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tfoot>
    {% for item in Orderan %}
    <tr>
        <td>{{item.timestamp|date:"l, d F Y"}}</td>
        <td><a href="{% url 'orders:lihatOrder' item.order_id item.user.get_username %}" class="text-dark" >{{ item.order_id }}</a></td>
        <td><a href="{% url 'akunLain' item.user.get_username %}"  class="text-dark" > {{ item.user.first_name }}  {{item.user.last_name}}</a></td>
        <td>Rp {{ item.Cart.total|floatformat|intcomma }}</td>
        <td>
        {% if item.buktiPembayaran %}
            <a href="{{ item.buktiPembayaran.url }}" class="btn btn-warning text-white">Lihat Bukti</a> 
        {% else %}
            <div class="btn btn-danger">Belum ada bukti</div>
        {% endif %}
        </td>
        <td><a class="btn btn-success" href="{% url 'orders:selesaikanOrder' item.order_id %}" class="text-white">Selesai</a></td>
    </tr>
    {% endfor %}
</table>
<br/>
</div>
{% endblock content %}

orders/templates/orders/upload.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
<title>Upload Bukti Pembayaran</title>
{% endblock title %}

{% block content %}
<div class="post">
    <div class="container">
        <div class="mx-auto jumbotron w-75">
            <div class="mx-auto w-75">
                {% if uploaded %}
                <h2>Terimakasih Telah Berbelanja di Hobbiku!</h2>
                {% else %}
                <h1>Upload Bukti Pembayaranmu Disini</h1>
                <form method="POST" enctype="multipart/form-data">
                    <table class="table">
                        {% csrf_token %}
                        <table style="border-collapse: separate;border-spacing: 0 15px">
                            <div class="row mb-3">
                                <div class="col-md-4">
                                    <label for="username"><b>Username</b></label>
                                </div>
                                <div class="col-md-8">
                                    {% if usrnm %}
                                    <input class="form-control" required="required" type="text" id="username"
                                        value="{{usrnm}}" name="username" placeholder="Username">
                                    {% else %}
                                    <input class="form-control" required="required" type="text" id="username"
                                        name="username" placeholder="Username">
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-4">
                                    <label for="order_id"><b>Id Transaksi</b></label>
                                </div>
                                <div class="col-md-8">
                                    {% if id_transaksi %}
                                    <input class="form-control" required="required" type="text" id="username"
                                        value="{{id_transaksi}}" name="order_id" placeholder="Id Transaksi">
                                    {% else %}
                                    <input class="form-control" required="required" type="text" id="username"
                                        name="order_id" placeholder="Id Transaksi">
                                    {% endif %}
                                </div>
                            </div>
                            <div class="row">
                            <div class="col-md-4">
                                <label for="buktiPembayaran"><b>Bukti Pembayaran</b></label>
                            </div>
                            <div class="col-md-8">
                            {{form|crispy}}
                            </div>
                            </div>
                        </table>

                    </table>
                    <button type="submit" class="btn btn-success">Upload</button>
                    {% if uploaded %}
                    <script>
                        msg();
                    </script>
                    {% endif %}
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    function msg() {
        alert("Tidak");
    }
</script>
{% endblock content %}

orders/templates/orders/user.html
{% extends 'base.html' %}
{% load humanize %}
{% load thumbnail %}

{% block title %}
<title>{{profile.first_name}} {{profile.last_name}}</title>
{% endblock title %}

{% block content %}
<div class="container-fluid w-75">

    <div class="row">

        <!-- Profile Picture -->
        <div class="col-md-6 pt-3">
            <div class="w-50 mx-auto mt-4">
                {% if profile.userprofileinfo.profile_pic %}
                {% thumbnail profile.userprofileinfo.profile_pic "200x200" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="rounded">
                {% endthumbnail %}
            </div>
        </div>
        {% endif %}

        <!-- Atributes -->
        <div class="col-md-6">
            <div class="bg-light p-4 rounded mb-4">
                <h3>Nama</h3>
                <h4>{{profile.first_name}} {{profile.last_name}}</h4>
                <h3>Username</h3>
                <h4>{{profile.username}}</h4>
                <h3>Alamat</h3>
                <h5>{{profile.userprofileinfo.alamat}} Kel {{profile.userprofileinfo.Kelurahan}}
                    Kec {{profile.userprofileinfo.Kecamatan}}, {{profile.userprofileinfo.Kota}},
                    {{profile.userprofileinfo.Provinsi}}</h5>
            </div>
        </div>
    </div>

    <!-- Riwayat Pembelian -->
    <div class="row">
        <table class="table table-striped mx-auto mt-20 w-100 bg-light link-dark">
            <thead class="thead-dark">
                <th>No.</th>
                <th>Tanggal</th>
                <th>ID Pesanan</th>
                <th>Harga Total</th>
                <th>Status</th>
            </thead>
            <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tfoot>
            {% for i in orderan %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{i.timestamp|date:"l, d F Y"}}</td>
                <td><a href="{% url 'orders:lihatOrder' i.order_id i.user.get_username %}">{{i.order_id}}</a></td>
                <td>Rp {{ i.Cart.total|floatformat|intcomma }}</td>
                {% if i.status == "Selesai"  %}
                <td>Selesai</td>
                {% else %}
                <td>Belum Selesai</td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock content %}