Hobby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views, settings
from orders.views import orders, akun_lain
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    url(r'^result/$', views.cari, name="cari"),
    path('menu/', include('menu.urls')),
    path('registrasi/', views.registrasi, name="register"),
    path('logout/', views.user_logout, name="logout"),
    path('user_login/', views.user_login, name="user_login"),
    path('cart/', include('cart.urls')),
    path('checkout/', include('orders.urls')),
    path('akun/', orders, name='akun'),
    path('tester/', views.test, name='test'),
    url(r'^(?P<username>[\w-]+)/$', akun_lain, name='akunLain'),
    

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.Cart, name='cart'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/$', views.tambahKeranjang, name='updateCart'),
    url(r'^(?P<id>[\w-]+)/$', views.removeKeranjang, name='removeKeranjang'),  
]

menu/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^(?P<category>[\w_]+)/$', views.indexCategory, name='category'),
    url(r'^(?P<category>[\w_]+)/(?P<slug>[\w-]+)$', views.beli, name='produkSatuan'),  
]

menu/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import datetime

class Category(models.Model):
    category_name = models.CharField(max_length=50)
    category_pic = models.ImageField(upload_to='menu/img/',blank=True)

    def __str__(self):
        return self.category_name

class Menu(models.Model):
    judulMenu = models.CharField(max_length=225)
    descMenu = models.TextField()
    picMenu = models.ImageField(upload_to='menu/img/',blank=True)
    posterMenu = models.ImageField(upload_to='menu/img/', blank=True)
    hargaMenu = models.IntegerField(default=0)
    diskon = models.IntegerField(default=0)
    kuantitas = models.IntegerField(default =  0)
    slug = models.SlugField(default='product-', unique=True)
    timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    active = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.judulMenu)

    class Meta:
        unique_together = ('judulMenu','slug')

    def get_price(self):
        return self.hargaMenu
    
    def get_absolute_url(self):
        return reverse("menu:produkSatuan", kwargs={"Slug":self.Slug})

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #addtional
    alamat = models.TextField(max_length=128)
    Provinsi = models.CharField(max_length=64)
    Kota = models.CharField(max_length=64)
    Kecamatan = models.CharField(max_length=64)
    Kelurahan = models.CharField(max_length=64)
    profile_pic = models.ImageField(upload_to ='profile/profile_pics', blank=True)
    

    def __str__(self):
        return self.user.username

class VariationManager(models.Manager):
    def all(self):
        return super(VariationManager, self).filter(active=True)
    
    def sizes(self):
        return self.all().filter(category='size')

    def colors(self):
        return self.all().filter(category='color')

VAR_CATEGORIES = (
    ('size', 'size'),
    ('color', 'color'),
    ('package', 'package'),
)

class Variation(models.Model):
    product = models.ForeignKey('Menu', on_delete=models.CASCADE)
    category = models.CharField(max_length=120, choices=VAR_CATEGORIES, default='size')
    title = models.CharField(max_length=120)
    updated = models.DateTimeField(auto_now_add=False,auto_now=True)
    active = models.BooleanField(default=True)

    objects = VariationManager()

    def __str__(self):
        return self.title

menu/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class FormCari(forms.Form):
    cari = forms.CharField()

class FormBeli(forms.Form):
    Jumlah = forms.IntegerField()

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email', 'password','first_name','last_name', 'email')

class UserProfileInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('Provinsi', 'Kota',
                  'Kecamatan', 'Kelurahan','alamat', 'profile_pic')
        labels = {
            "alamat": "Alamat",
        }

menu/views.py
from django.shortcuts import render, Http404
from django.http import HttpResponse
from django.db.models import Q
from .forms import FormBeli
from .models import Menu, Category
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    menus = Menu.objects.filter(kuantitas__gt=0)
    paginator = Paginator(menus, 3)

    try:
        item = paginator.page(page)
    except PageNotAnInteger:
        item = paginator.page(1)
    except EmptyPage:
        item = paginator.page(paginator.num_pages)

    context = {
        'title': 'Catalog',
        'subtitle': 'Catalog',
        'Menus': menus,
        'item':item,

    }
    return render(request, 'menu/menu.html', context)

def indexCategory(request, category):
    menus = {}
    page = request.GET.get('page', 1)

    menus = Menu.objects.filter(category=category,kuantitas__gt=0, active=True).order_by('timestamp')
    category_name = Category.objects.get(id = category)

    # if category == 'pria':
    #     menus = Menu.objects.filter(Q(JK__iexact='pria') | Q(JK__iexact='semua'),kuantitas__gt=0, active=True).order_by('timestamp')
    # elif category == 'wanita':
    #     menus = Menu.objects.filter(Q(JK__iexact='wanita') | Q(JK__iexact='semua'), kuantitas__gt=0, active=True).order_by('timestamp')
    # else:
    #     menus = Menu.objects.filter(kuantitas__gt=0, active=True).order_by('timestamp').order_by('timestamp')
    
    paginator = Paginator(menus, 8)
    

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'title': category_name.category_name,
        'category':category,
        'subtitle': 'Catalog',
        'Menus': posts,
        # 'posts':posts,

    }
    return render(request, 'menu/menu.html', context)

def beli(request, category,slug):
    try:
        FormBelii = FormBeli()

        pilihan = Menu.objects.get(slug=slug)
        pilihann = Menu.objects.filter(
            slug=slug).values_list('judulMenu', 'hargaMenu')
    except:
        raise Http404
    context = {
        'title': 'Order',
        'subtitle': pilihan.judulMenu,
        'Menus': pilihan,
        'FormMenu': FormBelii,
    }
    return render(request, 'menu/beli.html', context)

menu/templates/menu/beli.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load thumbnail %}

{% block title %}
<title>{{ Menus.judulMenu }}</title>
{% endblock title %}
{% block content %}
<article class="post">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 postingan ">
        <img src="{{ Menus.picMenu.url }}" width="400px" alt="Sample Image" class="item-image CustomShadow" />
      </div>
      <div class="col-md-6">
        <div id="container-beli" class="bg-light CustomShadow">
          <h2>{{item_name}}</h2>

          <p>{{Menus.descMenu}}</p>
          <h3>Rp. {{Menus.hargaMenu|intcomma}},-</h3>
          <div class="aksi">
            <form method="POST" action="{% url 'cart:updateCart' Menus.id Menus.slug %}">
              {% csrf_token %}
              <div class="col-sm-12">
                <div class="row mb-2 mt-4 beli__quantity">
                  <span>QTY : </span>
                  <input class="form-control" name="qty" type="number" value="1" placeholder="Jumlah"
                    style="display: inline; width: 20%;">
                </div>
                <div class="row mb-2">
                  {% if Menus.variation_set.all %}
                  {% if Menus.variation_set.sizes %}
                  <select class="form-control" name="size">
                    <option value="" disabled selected>Ukuran</option>
                    {% for item in Menus.variation_set.sizes %}
                    <option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
                    {% endfor %}
                  </select>
                  {% endif %}
                </div>
                <div class="row mb-2">
                  {% if Menus.variation_set.colors %}
                  <select class="form-control" name="color">
                    <option value="" disabled selected>Warna</option>
                    {% for item in Menus.variation_set.colors %}
                    <option value="{{ item.title|lower }}">{{ item.title|capfirst }}</option>
                    {% endfor %}
                  </select>
                  {% endif %}
                  {% endif %}
                </div>
                <div class="row mb-2"><input class="btn btn-success" type="submit" value="Masukan Keranjang"></div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</article>
{% endblock content %}

menu/templates/menu/cari.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}
<title>Hasil Pencarian</title>
{% endblock title %}
{% block content %}
<article class="post">
    <div class="row">
        {% for menu in Menus %}
        <div class="col-sm-3">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{ menu.picMenu.url }}" alt="">
                <div class="card-body">
                    <h5 class="card-title">{{menu.judulMenu}}</h5>
                    <h5 class="card-text text-info">Rp {{menu.hargaMenu|intcomma}}</h5>
                    <p class="card-text">{{menu.descMenu|truncatewords:15}}</p>
                    <a href="{% url 'menu:produkSatuan' menu.JK menu.slug %}" class="btn btn-success">Lihat</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</article>
{% endblock content %}

menu/templates/menu/menu.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load thumbnail %}


{% block title %}
<title>Catalogg</title>
{% endblock title %}

{% block content %}
<article class="post">
  <div class="container">
    <h3>{{ title }}</h3>
    <div class="row pilihan">
      {% for menu in Menus %}
      <div class="col-sm-2">
        <div class="card" style="">
          {% thumbnail menu.picMenu "300x300" crop="80% center" as im %}
          <a href="{% url 'menu:produkSatuan' category menu.slug %}"> <img class="card-img-top" src="{{ im.url }}"
              width="{{ im.width }}" height="{{ im.height }}"></a>
          {% endthumbnail %}
          <div class="card-body">
            <h5 class="card-title">{{menu.judulMenu}}</h5>
            <h5 class="card-text text-info">Rp {{menu.hargaMenu|intcomma}}</h5>
            {% comment %} <p class="card-text">{{menu.descMenu|truncatewords:15}}</p> {% endcomment %}
            <button class="btn btn-success" onclick="window.location.href='{{menu.slug}}'">Lihat Produk</button>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="row">
      {% if Menus.has_other_pages %}
      <ul class="pagination">
        {% if Menus.has_previous %}
        <li><a class="btn btn-outline-info mb-4 mr-2" href="?page={{ Menus.previous_page_number }}">«</a></li>
        {% else %}
        <li class="disabled btn btn-outline-info mb-4 mr-2"><span>«</span></li>
        {% endif %}
        {% for i in Menus.paginator.page_range %}
        {% if Menus.number == i %}
        <li class="active btn btn-outline-info mb-4 mr-2"><span>{{ i }} <span class="sr-only">(current)</span></span>
        </li>
        {% else %}
        <li><a class="btn btn-outline-info mb-4 mr-2" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if Menus.has_next %}
        <li><a class="btn btn-outline-info mb-4 mr-2" href="?page={{ Menus.next_page_number }}">»</a></li>
        {% else %}
        <li class="disabled btn btn-outline-info mb-4 mr-2"><span>»</span></li>
        {% endif %}
      </ul>
      {% endif %}
    </div>
  </div>
</article>
{% endblock content %}