Hobby/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views, settings
from orders.views import orders, akun_lain
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    url(r'^result/$', views.cari, name="cari"),
    path('menu/', include('menu.urls')),
    path('registrasi/', views.registrasi, name="register"),
    path('logout/', views.user_logout, name="logout"),
    path('user_login/', views.user_login, name="user_login"),
    path('cart/', include('cart.urls')),
    path('checkout/', include('orders.urls')),
    path('akun/', orders, name='akun'),
    path('tester/', views.test, name='test'),
    url(r'^(?P<username>[\w-]+)/$', akun_lain, name='akunLain'),
    

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.Cart, name='cart'),
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/$', views.tambahKeranjang, name='updateCart'),
    url(r'^(?P<id>[\w-]+)/$', views.removeKeranjang, name='removeKeranjang'),  
]

menu/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
    url(r'^(?P<category>[\w_]+)/$', views.indexCategory, name='category'),
    url(r'^(?P<category>[\w_]+)/(?P<slug>[\w-]+)$', views.beli, name='produkSatuan'),  
]

orders/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.Checkout, name='Checkout'),
    path('upload-bukti/', views.uploadBukti, name='uploadBukti'),
    path("pesanan-masuk/", views.pesanan_masuk, name="pesananMasuk"),
    url(r'^(?P<id>[\w-]+)/$', views.selesaikanOrder, name='selesaikanOrder'),
    url(r'^(?P<id>[\w-]+)/(?P<user>[\w-]+)/$', views.lihatOrder, name='lihatOrder'),
    
]

templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}

  {% endblock title %}

  <script src="{% static 'js/modernizr.min.js' %}" type="text/javascript"></script>
  <link href='https://fonts.googleapis.com/css?family=Nunito:400,300,700|Righteous' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
</head>

<body>
  <header class="header">
    <div class="container">
      <h1 class="site-title">Hobbiku</h1>
      <div class="site-tagline">
        <span class="site-tagline">Khilaf apa hari ini?</span><br>
        <div class="loginLogout">
          {% if user.is_authenticated %}
          <div class="dropdown show">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Account
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a class="dropdown-item" href="{% url 'akun' %}">Profile</a>
              <a class="dropdown-item" href="{% url 'orders:pesananMasuk' %}">Pesanan Masuk <span
                  class="badge badge-secondary">{{ request.session.JumlahPesanan }}</span></a>
              <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
              <a class="dropdown-item" href="{% url 'orders:uploadBukti' %}">Upload Bukti</a>
            </div>
          </div>

          {% else %}
          <a href="{% url 'user_login' %}">Login</a>
          {% endif %}
        </div>
      </div>
    </div>
  </header>

  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Home</a>
        </li>

        {% comment %} <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="{% url 'menu:category' 'semua' %}" id="navbarDropdown" role="button"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Category
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'menu:category' 'semua' %}">Semua</a>
            <a class="dropdown-item" href="{% url 'menu:category' 'pria' %}">Pria</a>
            <a class="dropdown-item" href="{% url 'menu:category' 'wanita' %}">Wanita</a>
        </li> {% endcomment %}

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'register' %}">Daftar</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'cart:cart' %}">Cart <span
              class="badge badge-pill badge-secondary">{{ request.session.item_total }}</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'cart:cart' %}">Unique Request <span
              class="badge badge-pill badge-secondary">{{ request.session.item_total }}</span></a>
        </li>
      </ul>

      <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'cari' %}">
        <input class="form-control mr-sm-2" type="text" name="cari" class="searchTerm"
          placeholder="Silahkan Cari Disini!" aria-label="Search">
        <button type="submit" class="btn btn-success my-2 my-sm-0">Cari</button>
      </form>
    </div>
  </nav>
  <!-- End Navbar -->


  <section class="content">
    <article class="post">
      <h2>{{subtitle}}</h2>
      </div>
    </article>

    {% block jumbotron %}

    {% endblock jumbotron %}

    <div class="konten">

      {% block content %}

      {% endblock content %}

    </div>
  </section>

  {% comment %} <footer class="footer">
    <div class="container">
      <p>Footer Text, Yo. Made with love by <a href="http://zulfikarchamim.blogspot.com">Zulfikar Chamim</a></p>
    </div>
  </footer> {% endcomment %}

  <footer class="storepage-extend">
    <div class="contact">
      <div class="contact__help">
        <h4>Features</h4>
        <ul>
          <li><a href="#" target="_blank" rel="noreferrer noopener">Help Center</a></li>
          <li></li>
          <li><a class="" href="#">Unique Request</a></li>
          <li><a href="#">Partner Area (B2B Platform)</a></li>
        </ul>
      </div>
      <div class="contact__help">
        <h4>Sound Your Idea!</h4>
        <ul>
          <li><a href="#" target="_blank" rel="noreferrer noopener">Lapor Bug</a></li>
          <li><a href="#" target="_blank" rel="noreferrer noopener">Feedback</a></li>
        </ul>
      </div>
      <div class="contact__tos">
        <h4>Terms of Service</h4>
        <ul>
          <li><a class="" href="#">Privacy Policy</a></li>
        </ul>
      </div>
      <div class="contact__location">
        <h4>Visit Hobbiku</h4>
        <ul>
          <li><a href="#" target="_blank" title="Go To Alpha" rel="noopener noreferrer">[Toko
              Tutup, Dalam Renovasi]<br>Sentra Niaga 5 Blok SN5-9 No.39, Kota Harapan Indah, Pusaka Rakyat, Tarumajaya,
              Bekasi Barat, 17214<br>(Seberang Bank BCA / Setelah Halte Busway Pasar Modern)</a></li>
        </ul>
      </div>
      <div class="contact__sosmed">
        <h4>Interact with Hobbiku</h4>
        <ul>
          <li>
            <a href="#" target="_blank" title="Facebook Hobbiku" rel="noopener noreferrer"><img src="{% static 'img/facebook.svg' %}" alt="Facebook Hobbiku"></a>
            <a href="#" target="_blank" title="Line Hobbiku" rel="noopener noreferrer"><img src="{% static 'img/line.svg' %}" alt="Line Hobbiku"></a>
            <a href="#" target="_blank" title="Instagram Hobbiku" rel="noopener noreferrer"><img src="{% static 'img/instagram.svg' %}" alt="Instagram Hobbiku"></a>
            <a href="#" target="_blank" title="Messenger Hobbiku" rel="noopener noreferrer"><img src="{% static 'img/messenger_square.svg' %}" alt="Messenger Hobbiku"></a>
            <a href="#" target="_blank" title="WhatsApp Hobbiku" rel="noopener noreferrer"><img src="{% static 'img/whatsapp.svg' %}" alt="WhatsApp Hobbiku"></a>
          </li>
          <li><img src="/static/img/icon/phone.png" alt="phone">0859 5666 5446</li>
          <li><img src="/static/img/icon/mail.png" alt="mail">support@hobbiku.com</li>
        </ul>
      </div>
    </div>
    <div class="copyright"><img src="/static/img/logo/hobbiku.png" alt="hobbiku.com"><span class="tagline">Ayo cintai hobimu
        bareng Hobbiku!</span><span class="copy">© 2014-2020 Hobbiku </span></div>
  </footer>
  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/script.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load humanize %}

{% block title %}
<title>Home</title>
{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    {% comment %} {% for poster in carousel %}
    <div class="card mb-3 w-50">
      <img src="{{ poster.posterMenu.url }}" class="card-img-top" alt="..." style="object-fit: cover; height:300px;">
      <div class="card-body">
        <h5 class="card-title">{{poster.judulMenu}}</h5>
        <p class="card-text">{{poster.descMenu|truncatewords:15}}</p>
      </div>
    </div>
    {% endfor %} {% endcomment %}
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        {% for img in carousel %}
        <div class="carousel-item">
          <img class="d-block w-100" src="{{ img.posterMenu.url }}" alt="Second slide">
        </div>
        {% endfor %}
        {% comment %} <div class="carousel-item">
          <img class="d-block w-100" src="https://www.greenscene.co.id/wp-content/uploads/2019/11/Luffy-696x497.jpg"
            alt="Third slide">
        </div> {% endcomment %}
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

  <div class="div__category">
    <h3>Category</h3>
    <div class="thumbnail-categories">
      {% for category in categories %}
      <div class="item_category" style="">
        <a href="{% url 'menu:category' category.id %}">
          <img src="{{ category.category_pic.url }}" class="card-img-top">
          <h5 class="item_title">{{ category.category_name }}</h5>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>

  <h3 class="mt-4">Produk Terbaru Di Distroku</h3>
  <div class="row mx-auto pb-10">
    {% for menu in Menu %}
    <div class="col-sm-2 ">
      <div class="card w-100">
        {% thumbnail menu.picMenu "300x300" crop="80% center" as im %}
        <img class="card-img-top" src="{{im.url}}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        <div class="card-body">
          <h5 class="card-title">{{menu.judulMenu}}</h5>
          <h5 class="card-text text-info">Rp {{menu.hargaMenu|intcomma}}</h5>
          <a class="btn btn-success text-white" href="{% url 'menu:produkSatuan' 'semua' menu.slug %}">Lihat Produk</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>


</div>


{% endblock content %}


{% comment %} <div class="post">
  <h3>{{poster.judulMenu}}</h3>
  <a href="{% url 'menu:produkSatuan' poster.JK poster.slug %}">
    <img src="{{ poster.posterMenu.url }}" style="width:100%;">
  </a>
</div> {% endcomment %}

templates/login.html
{% extends 'base.html' %}
{% block title %}
<title>Login</title>
{% endblock title %}


{% block content %}
<form id="form-login" class="mx-auto" action="{% url 'user_login' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="username">Username</label>
        <input type="text" name="username" class="form-control" placeholder="Masukan Username">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" class="form-control" placeholder="Masukan Password">
    </div>
    <input type="submit" class="btn btn-primary" value="Login">
</form>
{% endblock content %}

templates/registrasi.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Pendaftaran</title>
{% endblock title %}

{% block content %}
<div class="container">
    <div class="mx-auto jumbotron w-75" >
        {% if registered %}
            <h1>Thank you for registering!</h1>
        {% else  %}
            <div class="mx-auto w-75">
            <h1>Register Here!</h1>
            <h3>Yuk, Isi data diri anda!</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                    {{ user_form|crispy }}
                    {{ profile_form|crispy }}
                <input class="btn btn-success" type="submit" name="" value="Register">
            </form>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}
    

templates/unique_requests.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row" style="justify-content: center;">
    <div class="div__reqUnique"
        style="border: 1px solid black; width: 22rem; padding: 1rem; border-radius: 5px; display: flex; flex-direction: column;">
        <span>Unique Request</span>
        <form action="POST">
            {% csrf_token %}
            <input type="text" name="reqUnique" id="" placeholder="Masukan Link Barang Yang Kamu Mau">
            <button type="submit" class="btn btn-success">Kirim</button>
        </form>
    </div>
</div>

{% endblock content %}